image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - before: nvm i 12 && nvm use 12 && npm i yarn gulp -g
    init: yarn install && yarn upgrade # runs during prebuild
    command: yarn build